# Generated by Django 2.0.2 on 2019-03-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190323_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='media/', verbose_name='イメージ'),
        ),
    ]
